services:
  - type: web
    name: wanderlust-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
    root: ./ # This specifies the root directory 